name = "local-news-videos"
main = "build/worker/shim.mjs"
compatibility_date = "2024-08-07"

[build]
command = "cargo install -q worker-build && worker-build --release"

[vars]
#GOOGLE_API_KEY="GOOGLE_API_KEY"
